import type { ReferenceEntry } from "./document-model";

export type CitationStyle = "apa-7" | "ieee" | "vancouver" | "harvard" | "chicago";
export interface CitationIssue { code: "UNCITED_REFERENCE" | "MISSING_REFERENCE" | "DUPLICATE_REFERENCE" | "INCOMPLETE_REFERENCE"; message: string; referenceId?: string; token?: string; severity: "warning" | "error"; }
export interface CitationAnalysis { references: ReferenceEntry[]; citedReferenceIds: string[]; issues: CitationIssue[]; }

const doiPattern = /(?:https?:\/\/doi\.org\/|doi:\s*)(10\.\d{4,9}\/[\w.()/:;-]+)/i;
const urlPattern = /https?:\/\/[^\s)]+/i;
const yearPattern = /\b(19|20)\d{2}\b/;
const numericCitationPattern = /\[(\d+(?:\s*[,;–-]\s*\d+)*)\]/g;
const authorYearPattern = /\(([A-Z][A-Za-zÀ-ÿ'’-]+(?:\s+et\s+al\.)?,?\s+(?:19|20)\d{2}[a-z]?)\)/g;

function stableId(raw: string, index: number): string { const normalized = raw.toLowerCase().replace(/\s+/g, " ").trim(); let hash = 0; for (let cursor = 0; cursor < normalized.length; cursor += 1) hash = (hash * 31 + normalized.charCodeAt(cursor)) | 0; return `ref-${index + 1}-${Math.abs(hash)}`; }
function parseAuthors(raw: string): string[] { const authorPart = raw.split(/[.(]\s*(?:19|20)\d{2}/)[0].trim().replace(/\s+and\s+/gi, ";").replace(/\s*&\s*/g, ";"); return authorPart.split(/;|,\s+(?=[A-Z][a-z]+\s)/).map((author) => author.trim()).filter(Boolean).slice(0, 20); }
function classify(raw: string): ReferenceEntry["type"] { if (/\b(thesis|skripsi|dissertation)\b/i.test(raw)) return "thesis"; if (/https?:\/\//i.test(raw)) return "website"; if (/\b(journal|vol\.?|no\.?\s*\d|proceedings)\b/i.test(raw)) return "article"; if (raw.split(".").length > 2) return "book"; return "unknown"; }
export function parseReference(raw: string, index: number): ReferenceEntry { const trimmed = raw.trim(); const yearMatch = trimmed.match(yearPattern); const year = yearMatch?.[0]; const doi = trimmed.match(doiPattern)?.[1]; const url = trimmed.match(urlPattern)?.[0]?.replace(/[.,]$/, ""); const withoutAuthors = trimmed.replace(/^[-*\d.)\s]+/, ""); const afterYear = yearMatch && yearMatch.index !== undefined ? trimmed.slice(yearMatch.index + yearMatch[0].length).replace(/^\)?[.: -]*/, "").trim() : withoutAuthors; const title = afterYear.split(/\.\s+/)[0].replace(/[.]+$/, "").trim(); const completeness = [year, doi || url, title.length > 5 ? title : undefined, parseAuthors(trimmed).length ? "author" : undefined].filter(Boolean).length / 4; return { id: stableId(trimmed, index), type: classify(trimmed), title, authors: parseAuthors(trimmed), year: year ? Number(year) : undefined, doi, url, raw: trimmed, completeness }; }
export function parseReferences(input: string): ReferenceEntry[] { return input.split(/\n+/).map((line) => line.trim()).filter((line) => line && !/^daftar pustaka$/i.test(line) && !/^references?$/i.test(line)).map(parseReference); }
export function extractCitationTokens(content: string): string[] { const numericTokens: string[] = []; let numericMatch = numericCitationPattern.exec(content); while (numericMatch) { numericTokens.push(numericMatch[0]); numericMatch = numericCitationPattern.exec(content); } numericCitationPattern.lastIndex = 0; const authorYearTokens: string[] = []; let authorYearMatch = authorYearPattern.exec(content); while (authorYearMatch) { authorYearTokens.push(authorYearMatch[0]); authorYearMatch = authorYearPattern.exec(content); } authorYearPattern.lastIndex = 0; return [...numericTokens, ...authorYearTokens]; }
export function analyzeCitations(content: string, references: ReferenceEntry[]): CitationAnalysis { const tokens = extractCitationTokens(content); const citedReferenceIds = references.filter((reference, index) => tokens.some((token) => token.includes(`[${index + 1}]`) || (reference.year && token.includes(String(reference.year))))).map((reference) => reference.id); const issues: CitationIssue[] = []; const seen = new Map<string, string>(); references.forEach((reference) => { const key = `${reference.title.toLowerCase()}|${reference.year ?? ""}`; if (seen.has(key)) issues.push({ code: "DUPLICATE_REFERENCE", message: "Referensi tampak duplikat.", referenceId: reference.id, severity: "warning" }); else seen.set(key, reference.id); if (reference.completeness < 0.75) issues.push({ code: "INCOMPLETE_REFERENCE", message: "Data referensi belum lengkap.", referenceId: reference.id, severity: "warning" }); if (!citedReferenceIds.includes(reference.id)) issues.push({ code: "UNCITED_REFERENCE", message: "Referensi belum ditemukan dalam sitasi isi.", referenceId: reference.id, severity: "warning" }); }); tokens.filter((token) => /^\[/.test(token)).forEach((token) => { const numbers = token.match(/\d+/g)?.map(Number) ?? []; numbers.forEach((number) => { if (!references[number - 1]) issues.push({ code: "MISSING_REFERENCE", message: `Sitasi ${token} belum memiliki referensi nomor ${number}.`, token, severity: "error" }); }); }); return { references, citedReferenceIds, issues }; }
function authorText(reference: ReferenceEntry): string { return reference.authors.length ? reference.authors.join(", ") : "[Penulis perlu dilengkapi]"; }
export function formatReference(reference: ReferenceEntry, style: CitationStyle, index: number): string { const year = reference.year ? `(${reference.year})` : "(n.d.)"; const title = reference.title || "[Judul perlu dilengkapi]"; if (style === "ieee" || style === "vancouver") return `[${index + 1}] ${authorText(reference)}, “${title},” ${reference.doi ? `doi: ${reference.doi}` : reference.url ?? ""}.`; if (style === "chicago") return `${authorText(reference)}. ${year}. “${title}.” ${reference.url ?? reference.doi ?? ""}`.trim(); return `${authorText(reference)}. ${year}. ${title}. ${reference.doi ? `https://doi.org/${reference.doi}` : reference.url ?? ""}`.trim(); }


