import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";
import type { DocumentBlock, SkripsiDocument } from "./document-model";
import type { InlineSegment } from "./ingestion";

export interface PdfExportResult { filename: string; mimeType: "application/pdf"; data: ArrayBuffer; }
const PAGE_WIDTH = 595.28; const PAGE_HEIGHT = 841.89; const MARGIN_X = 72; const MARGIN_TOP = 70; const MARGIN_BOTTOM = 65; const LINE_HEIGHT = 17;
function safeFilename(filename: string): string { const normalized = filename.normalize("NFKC").replace(/[^\w .-]/g, "-").trim(); return `${(normalized || "skripsiflow-document").slice(0, 120).replace(/\.pdf$/i, "")}.pdf`; }
function segmentsFor(block: DocumentBlock): InlineSegment[] { try { const parsed = block.metadata?.inline ? JSON.parse(block.metadata.inline) as InlineSegment[] : []; return parsed.length ? parsed : [{ text: block.content, marks: [] }]; } catch { return [{ text: block.content, marks: [] }]; } }
function fontFor(fonts: Record<string, PDFFont>, marks: string[]): PDFFont { if (marks.includes("bold") && marks.includes("italic")) return fonts.boldItalic; if (marks.includes("bold")) return fonts.bold; if (marks.includes("italic")) return fonts.italic; return fonts.normal; }
function drawWrapped(page: PDFPage, segments: InlineSegment[], fonts: Record<string, PDFFont>, x: number, y: number, maxWidth: number, size: number): number { let cursorX = x; let cursorY = y; for (const segment of segments) { const font = fontFor(fonts, segment.marks); const words = segment.text.split(/(\s+)/); for (const word of words) { const width = font.widthOfTextAtSize(word, size); if (cursorX > x && cursorX + width > x + maxWidth) { cursorX = x; cursorY -= LINE_HEIGHT; } page.drawText(word, { x: cursorX, y: cursorY, size, font, color: rgb(0.09, 0.13, 0.11) }); if (segment.marks.includes("underline") && word.trim()) page.drawLine({ start: { x: cursorX, y: cursorY - 2 }, end: { x: cursorX + width, y: cursorY - 2 }, thickness: 0.7, color: rgb(0.09, 0.13, 0.11) }); cursorX += width; } } return cursorY; }
function blockSize(block: DocumentBlock): { size: number; gap: number } { if (block.type === "chapter") return { size: 16, gap: 22 }; if (block.type === "section") return { size: 14, gap: 16 }; if (block.type === "subchapter") return { size: 13, gap: 13 }; if (block.type === "quote") return { size: 11, gap: 12 }; return { size: block.type === "reference" ? 11 : 12, gap: 12 }; }
export async function exportPdf(document: SkripsiDocument, filename = "skripsiflow-document.pdf"): Promise<PdfExportResult> { if (!document.title.trim()) throw new Error("Dokumen belum memiliki judul."); const pdf = await PDFDocument.create(); const fonts = { normal: await pdf.embedFont(StandardFonts.TimesRoman), bold: await pdf.embedFont(StandardFonts.TimesRomanBold), italic: await pdf.embedFont(StandardFonts.TimesRomanItalic), boldItalic: await pdf.embedFont(StandardFonts.TimesRomanBoldItalic) }; let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]); let y = PAGE_HEIGHT - MARGIN_TOP; for (const block of document.blocks) { const { size, gap } = blockSize(block); const segments = segmentsFor(block); const estimated = segments.reduce((sum, segment) => sum + segment.text.length, 0) / 75 * LINE_HEIGHT; if (y - estimated < MARGIN_BOTTOM) { page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]); y = PAGE_HEIGHT - MARGIN_TOP; } if (block.type === "table") { const rows = block.content.split(/\n/).filter(Boolean); for (const row of rows) { page.drawRectangle({ x: MARGIN_X, y: y - 16, width: PAGE_WIDTH - MARGIN_X * 2, height: 20, borderColor: rgb(0.75, 0.8, 0.76), borderWidth: 0.6 }); y = drawWrapped(page, [{ text: row.replace(/\|/g, "  |  "), marks: [] }], fonts, MARGIN_X + 6, y - 13, PAGE_WIDTH - MARGIN_X * 2 - 12, 10) - 8; } } else { y = drawWrapped(page, segments, fonts, MARGIN_X, y, PAGE_WIDTH - MARGIN_X * 2, size) - gap; } } const data = await pdf.save(); return { filename: safeFilename(filename), mimeType: "application/pdf", data: data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer }; }
