import JSZip from "jszip";
import type { DocumentBlock, SkripsiDocument } from "./document-model";
import type { InlineSegment } from "./ingestion";
import { getTemplate, resolveBlockStyle } from "./template";

export interface ExportResult { filename: string; mimeType: string; data: ArrayBuffer; }
const escapeXml = (value: string): string => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
const alignment = (value?: string): string => value ? `<w:jc w:val="${value}"/>` : "";
function runXml(text: string, style: { font: string; size: number }, marks: string[] = []): string { const markXml = `${marks.includes("bold") ? "<w:b/>" : ""}${marks.includes("italic") ? "<w:i/>" : ""}${marks.includes("underline") ? "<w:u w:val=\"single\"/>" : ""}`; return `<w:r><w:rPr><w:rFonts w:ascii="${style.font}" w:hAnsi="${style.font}"/><w:sz w:val="${style.size * 2}"/>${markXml}</w:rPr><w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r>`; } function paragraphXml(text: string, block: DocumentBlock, document: SkripsiDocument): string { const style = resolveBlockStyle(block, document.templateId); const properties = `<w:pPr><w:pStyle w:val="${style.styleId}"/>${alignment(style.alignment)}</w:pPr>`; let segments: InlineSegment[] = []; try { segments = block.metadata?.inline ? JSON.parse(block.metadata.inline) as InlineSegment[] : [{ text, marks: [] }]; } catch { segments = [{ text, marks: [] }]; } if (!segments.length) segments = [{ text, marks: [] }]; return `<w:p>${properties}${segments.map((segment) => runXml(segment.text, style, segment.marks)).join("")}</w:p>`; }
function tableXml(block: DocumentBlock): string { const rows = block.content.split(/\n/).filter(Boolean).map((row) => row.split("|").map((cell) => cell.trim()).filter(Boolean)); return `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/></w:tblPr>${rows.map((row) => `<w:tr>${row.map((cell) => `<w:tc><w:p><w:r><w:t>${escapeXml(cell)}</w:t></w:r></w:p></w:tc>`).join("")}</w:tr>`).join("")}</w:tbl>`; }
function documentXml(document: SkripsiDocument): string { const body = document.blocks.map((block) => block.type === "table" ? tableXml(block) : paragraphXml(block.content, block, document)).join(""); return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1800"/></w:sectPr></w:body></w:document>`; }
const stylesXml = (document: SkripsiDocument): string => { const template = getTemplate(document.templateId); const styles = Object.values(template.styles).map((style) => `<w:style w:type="paragraph" w:styleId="${style.styleId}"><w:name w:val="${style.styleId}"/><w:rPr><w:rFonts w:ascii="${style.font}" w:hAnsi="${style.font}"/><w:sz w:val="${style.size * 2}"/>${style.bold ? "<w:b/>" : ""}${style.italic ? "<w:i/>" : ""}</w:rPr></w:style>`).join(""); return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">${styles}</w:styles>`; };
function safeFilename(filename: string): string { const normalized = filename.normalize("NFKC").replace(/[^\w .-]/g, "-").trim(); return `${(normalized || "skripsiflow-document").slice(0, 120).replace(/\.docx$/i, "")}.docx`; }
export async function exportDocx(document: SkripsiDocument, filename = "skripsiflow-document.docx"): Promise<ExportResult> { if (!document.title.trim() || !document.templateId) throw new Error("Dokumen belum memiliki metadata wajib."); const outputFilename = safeFilename(filename); const zip = new JSZip(); zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`); zip.file("_rels/.rels", `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`); zip.file("word/_rels/document.xml.rels", `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>`); zip.file("word/document.xml", documentXml(document)); zip.file("word/styles.xml", stylesXml(document)); return { filename: outputFilename, mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", data: (await zip.generateAsync({ type: "arraybuffer" })) }; }

