import type { DocumentBlock, SkripsiDocument } from "./document-model";

export type InlineMark = "bold" | "italic" | "underline";
export interface InlineSegment { text: string; marks: InlineMark[]; }
export type InputKind = "markdown" | "plain-text" | "paste";
export interface SourceInput { kind: InputKind; name?: string; extension?: string; content: string; }
export interface IngestionIssue { code: "EMPTY_CONTENT" | "UNSUPPORTED_EXTENSION" | "CONTENT_TOO_LARGE" | "AMBIGUOUS_STRUCTURE"; message: string; line?: number; severity: "error" | "warning"; }
export interface IngestionResult { document: SkripsiDocument | null; issues: IngestionIssue[]; }
const MAX_CONTENT_LENGTH = 2_000_000; const SUPPORTED_EXTENSIONS = new Set([".md", ".markdown", ".txt"]);
function normalizeLineEndings(content: string): string { return content.replace(/^\uFEFF/, "").replace(/\r\n?/g, "\n"); }
export function parseInlineMarkdown(content: string): InlineSegment[] { const segments: InlineSegment[] = []; const pattern = /(\*\*|__|(?<!\*)\*(?!\*)|(?<!_)_(?!_)|~~|<u>|<\/u>)/g; let marks: InlineMark[] = []; let cursor = 0; let match: RegExpExecArray | null; const toggle = (mark: InlineMark) => { marks = marks.includes(mark) ? marks.filter((item) => item !== mark) : [...marks, mark]; }; while ((match = pattern.exec(content))) { if (match.index > cursor) segments.push({ text: content.slice(cursor, match.index), marks: [...marks] }); const token = match[0]; if (token === "**" || token === "__") toggle("bold"); else if (token === "*" || token === "_") toggle("italic"); else if (token === "~~") toggle("underline"); else if (token === "<u>") toggle("underline"); else toggle("underline"); cursor = match.index + token.length; } if (cursor < content.length) segments.push({ text: content.slice(cursor), marks: [...marks] }); return segments.filter((segment) => segment.text.length > 0); }
function confidenceFor(type: DocumentBlock["type"], content: string): number { if (type === "chapter") return 0.98; if (type === "section" || type === "subchapter") return 0.96; if (type === "paragraph") return content.trim().length > 30 ? 0.96 : 0.78; if (type === "list" || type === "quote") return 0.94; if (type === "table") return 0.86; return 0.7; }
function createBlock(type: DocumentBlock["type"], content: string, source: InputKind, index: number, line: number, inline?: InlineSegment[]): DocumentBlock { const confidence = confidenceFor(type, content); return { id: `block-${index + 1}`, type, content, confidence, confidenceLevel: confidence >= 0.9 ? "high" : confidence >= 0.8 ? "medium" : "low", source, needsReview: confidence < 0.9, metadata: { sourceLine: String(line), ...(inline ? { inline: JSON.stringify(inline) } : {}) } }; }
function detectHeading(line: string): { type: "chapter" | "section" | "subchapter"; content: string } | null { const trimmed = line.trim(); const markdown = trimmed.match(/^(#{1,6})\s+(.+)$/); if (markdown) { const heading = markdown[2].trim(); if (/^BAB\s+[IVXLCDM0-9]+\b/i.test(heading) || markdown[1].length === 1) return { type: "chapter", content: heading }; if (markdown[1].length === 2 || /^\d+\.\d+\s/.test(heading)) return { type: "section", content: heading }; return { type: "subchapter", content: heading }; } if (/^BAB\s+[IVXLCDM0-9]+(?:\s*[-:.].*)?$/i.test(trimmed)) return { type: "chapter", content: trimmed }; if (/^\d+\.\d+\.\d+\s+.+/.test(trimmed)) return { type: "subchapter", content: trimmed }; if (/^\d+(?:\.\d+)+[.)]?\s+.+/.test(trimmed)) return { type: "section", content: trimmed }; return null; }

const HEADING_KEYWORDS=new Set(["latar belakang","rumusan masalah","identifikasi masalah","batasan masalah","tujuan penelitian","manfaat penelitian","tinjauan pustaka","landasan teori","kerangka berpikir","hipotesis","metode penelitian","jenis penelitian","populasi dan sampel","teknik pengumpulan data","instrumen penelitian","teknik analisis data","hasil penelitian","pembahasan","hasil dan pembahasan","kesimpulan","saran","daftar pustaka","lampiran","surat pernyataan","kata pengantar","abstrak","daftar isi","daftar tabel","daftar gambar","bab i","bab ii","bab iii","bab iv","bab v","bab vi","pendahuluan","kajian pustaka","metodologi penelitian","analisis data","penutup","bibliografi","riwayat hidup",]);const ROMAN_RE=/^[ivxlcdm]+$/i;function inferHeading(line,lineIndex,context){var t=line.trim();if(!t)return null;var m=t.match(/^bab\s+([ivxlcdm\d]+)[\.:]?\s+(.+)/i);if(m)return{type:"chapter",content:m[2].trim()};m=t.match(/^bab\s+([ivxlcdm]+)[\.:]?$/i);if(m)return{type:"chapter",content:"BAB "+m[1].toUpperCase()};m=t.match(/^(\d+)\.(\d+)\s+(.+)/);if(m)return{type:"section",content:m[3].trim()};m=t.match(/^([ivxlcdm]+)\.([ivxlcdm]+)\s+(.+)/i);if(m)return{type:"section",content:m[3].trim()};m=t.match(/^(\d+)\.(\d+)\.(\d+)\s+(.+)/);if(m)return{type:"subchapter",content:m[4].trim()};m=t.match(/^([ivxlcdm]+)\.([ivxlcdm]+)\.([ivxlcdm]+)\s+(.+)/i);if(m)return{type:"subchapter",content:m[4].trim()};m=t.match(/^([ivxlcdm]+)[\.:\)]\s+(.+)$/i);if(m&&ROMAN_RE.test(m[1]))return{type:context.inChapter?"section":"chapter",content:m[2].trim()};var hU=/[A-Z]/.test(t),hL=/[a-z]/.test(t);if(hU&&!hL&&t.length>3&&t.length<100&&!t.endsWith(".")&&!t.endsWith(":")){var w=t.split(/\s+/);if(w.length>=2||t.length>10)return{type:context.inChapter?"section":"chapter",content:t}}var l=t.toLowerCase().replace(/[\.:\;]+$/,"");if(HEADING_KEYWORDS.has(l))return{type:context.inChapter?"section":"chapter",content:t};if(t.length>10&&t.length<70&&!t.endsWith(".")&&!t.endsWith(":")&&!t.endsWith(";")){var w=t.split(/\s+/);if(w.length<=5&&w.length>=2)return{type:context.inChapter?"section":"chapter",content:t}}return null;}

function parseBlocks(input: SourceInput): { blocks: DocumentBlock[]; issues: IngestionIssue[] } { const lines = normalizeLineEndings(input.content).split("\n"); const blocks: DocumentBlock[] = []; const issues: IngestionIssue[] = []; let paragraph: string[] = []; let paragraphLine = 1; let index = 0; const flushParagraph = () => { const raw = paragraph.join(" ").replace(/\s+/g, " ").trim(); if (!raw) return; const content = raw.replace(/^([-*+]\s+|\d+[.)]\s+)/, ""); const type = /^[-*+]\s+|^\d+[.)]\s+/.test(raw) ? "list" : "paragraph"; blocks.push(createBlock(type, content, input.kind, index++, paragraphLine, parseInlineMarkdown(content))); paragraph = []; }; for (let cursor = 0; cursor < lines.length; cursor += 1) { const line = lines[cursor]; const trimmed = line.trim(); if (!trimmed) { flushParagraph(); continue; } const heading = detectHeading(line); if (heading) { flushParagraph(); blocks.push(createBlock(heading.type, heading.content.replace(/^#{1,6}\s+/, ""), input.kind, index++, cursor + 1, parseInlineMarkdown(heading.content))); continue; } var inferred = inferHeading(line, cursor + 1, { inChapter: blocks.some(function(b) { return b.type === "chapter"; }) }); if (inferred) { flushParagraph(); var bt = inferred.type === "chapter" ? "chapter" : inferred.type === "subchapter" ? "subchapter" : "section"; blocks.push(createBlock(bt, inferred.content, input.kind, index++, cursor + 1, parseInlineMarkdown(inferred.content))); continue; } if (/^\|.*\|$/.test(trimmed)) { flushParagraph(); blocks.push(createBlock("table", trimmed, input.kind, index++, cursor + 1)); continue; } if (/^>\s+/.test(trimmed)) { flushParagraph(); const content = trimmed.replace(/^>\s+/, ""); blocks.push(createBlock("quote", content, input.kind, index++, cursor + 1, parseInlineMarkdown(content))); continue; } if (!paragraph.length) paragraphLine = cursor + 1; paragraph.push(trimmed.replace(/^```.*|```$/g, "").trim()); } flushParagraph(); if (blocks.some((block) => block.needsReview)) issues.push({ code: "AMBIGUOUS_STRUCTURE", message: "Beberapa bagian perlu dikonfirmasi sebelum diekspor.", severity: "warning" }); return { blocks, issues }; }
export function ingestSource(input: SourceInput): IngestionResult { const content = normalizeLineEndings(input.content); const issues: IngestionIssue[] = []; if (!content.trim()) issues.push({ code: "EMPTY_CONTENT", message: "Dokumen masih kosong.", severity: "error" }); if (content.length > MAX_CONTENT_LENGTH) issues.push({ code: "CONTENT_TOO_LARGE", message: "Ukuran dokumen melebihi batas 2 MB.", severity: "error" }); if (input.extension && !SUPPORTED_EXTENSIONS.has(input.extension.toLowerCase())) issues.push({ code: "UNSUPPORTED_EXTENSION", message: "Format file harus .md, .markdown, atau .txt.", severity: "error" }); if (issues.some((issue) => issue.severity === "error")) return { document: null, issues }; const parsed = parseBlocks({ ...input, content }); const now = new Date().toISOString(); return { issues: [...issues, ...parsed.issues], document: { schemaVersion: 1, id: `session-${Date.now()}`, title: input.name?.replace(/\.(md|markdown|txt)$/i, "") || "Dokumen baru", templateId: "indonesia-standard-v1", citationStyle: "apa-7", blocks: parsed.blocks, references: [], reviewRequired: parsed.blocks.some((block) => block.needsReview), createdAt: now, updatedAt: now } }; }

export function changeBlockType(blockId, type) { console.warn("changeBlockType not implemented in ingestion module"); }
