"use client";
import { ChangeEvent, DragEvent, useMemo, useState } from "react";
import { ingestSource } from "../../lib/ingestion";
import type { DocumentBlock, SkripsiDocument } from "../../lib/document-model";
const styles = ["APA 7", "IEEE", "Vancouver", "Harvard", "Chicago"];
export default function WorkspacePage() {
  const [document, setDocument] = useState<SkripsiDocument | null>(null); const [paste, setPaste] = useState(""); const [selectedStyle, setSelectedStyle] = useState("APA 7"); const [draggedId, setDraggedId] = useState<string | null>(null); const [message, setMessage] = useState("Belum ada bahan masuk");
  const reviewCount = useMemo(() => document?.blocks.filter((block) => block.needsReview).length ?? 0, [document]);
  const parse = (content: string, kind: "paste" | "markdown" | "plain-text", name?: string, extension?: string) => { const result = ingestSource({ content, kind, name, extension }); if (!result.document) { setMessage(result.issues.map((issue) => issue.message).join(" ")); return; } setDocument({ ...result.document, citationStyle: selectedStyle.toLowerCase().replaceAll(" ", "-") }); setMessage(result.issues.length ? `${result.issues.length} hal perlu ditinjau` : "Struktur berhasil dikenali"); };
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const extension = `.${file.name.split(".").pop()?.toLowerCase()}`; if (![".md", ".markdown", ".txt"].includes(extension)) { setMessage("Gunakan file .md, .markdown, atau .txt"); return; } const reader = new FileReader(); reader.onload = () => parse(String(reader.result ?? ""), extension === ".txt" ? "plain-text" : "markdown", file.name, extension); reader.readAsText(file); };
  const drop = (event: DragEvent<HTMLLabelElement>) => { event.preventDefault(); const file = event.dataTransfer.files[0]; if (!file) return; const extension = `.${file.name.split(".").pop()?.toLowerCase()}`; if (![".md", ".markdown", ".txt"].includes(extension)) { setMessage("Gunakan file .md, .markdown, atau .txt"); return; } const reader = new FileReader(); reader.onload = () => parse(String(reader.result ?? ""), extension === ".txt" ? "plain-text" : "markdown", file.name, extension); reader.readAsText(file); };
  const reorder = (targetId: string) => { if (!document || !draggedId || draggedId === targetId) return; const blocks = [...document.blocks]; const from = blocks.findIndex((block) => block.id === draggedId); const to = blocks.findIndex((block) => block.id === targetId); const [moved] = blocks.splice(from, 1); blocks.splice(to, 0, moved); setDocument({ ...document, blocks, updatedAt: new Date().toISOString() }); setDraggedId(null); };
  const updateBlock = (block: DocumentBlock, content: string) => { if (!document) return; setDocument({ ...document, blocks: document.blocks.map((item) => item.id === block.id ? { ...item, content, source: "manual", needsReview: false, confidence: 1, confidenceLevel: "high" } : item), updatedAt: new Date().toISOString() }); };
  return <main className="workspace-page"><header className="workspace-header shell"><a className="brand" href="/"><span className="brand-mark">S</span><span>Skripsi<span className="brand-accent">Flow</span></span></a><div className="workspace-title"><span className="eyebrow">WORKSPACE</span><strong>{document?.title ?? "Dokumen baru"}</strong></div><button className="secondary-button" onClick={() => setDocument(null)}>Mulai ulang</button></header><section className="workspace shell"><aside className="input-panel"><p className="eyebrow">LANGKAH 01 / 04</p><h1>Masukkan<br /><em>bahanmu.</em></h1><p className="panel-copy">Upload file atau tempel teks dari AI. Struktur akan dibaca otomatis.</p><label className="dropzone" onDragOver={(event) => event.preventDefault()} onDrop={drop}><span className="upload-icon">↑</span><strong>Tarik file ke sini</strong><span>Markdown atau TXT</span><input type="file" accept=".md,.markdown,.txt,text/plain,text/markdown" onChange={upload} /></label><div className="paste-divider"><span>atau tempel langsung</span></div><textarea value={paste} onChange={(event) => setPaste(event.target.value)} placeholder="Tempel hasil AI atau tulisanmu di sini..." /><button className="primary-button full-button" onClick={() => parse(paste, "paste")}>Analisis bahan <span>→</span></button><p className="privacy-note">✦ File diproses sementara dan tidak masuk ke log.</p></aside><section className="review-panel"><div className="review-toolbar"><div><p className="eyebrow">LANGKAH 02 / 04</p><h2>Review struktur</h2></div><div className="toolbar-right"><label>Gaya referensi<select value={selectedStyle} onChange={(event) => setSelectedStyle(event.target.value)}>{styles.map((style) => <option key={style}>{style}</option>)}</select></label><span className={`review-status ${document ? "ready" : ""}`}>{document ? `${reviewCount} perlu review` : "Menunggu bahan"}</span></div></div>{!document ? <div className="empty-review"><span>✦</span><strong>Hasil analisismu akan muncul di sini</strong><p>Mulai dengan upload file atau paste bahan skripsi.</p></div> : <div className="block-list">{document.blocks.map((block) => <article className={`document-block ${block.needsReview ? "needs-review" : ""}`} key={block.id} draggable onDragStart={() => setDraggedId(block.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorder(block.id)}><span className="drag-handle">⠿</span><div className="block-content"><span className="block-type">{block.type} · {Math.round(block.confidence * 100)}%</span><textarea value={block.content} onChange={(event) => updateBlock(block, event.target.value)} /><small>{block.needsReview ? "Periksa struktur atau isi blok ini" : "Struktur terdeteksi dengan baik"}</small></div></article>)}</div>}<div className="review-footer"><span>{message}</span><button className="primary-button" disabled={!document || reviewCount > 0}>Lanjut ke template <span>→</span></button></div></section></section></main>;
}
